import axios, { AxiosRequestConfig } from "axios";
import { serverPath } from "../common";
const tkn = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5NTE0MTE2NDIwIiwicm9sZXMiOiJBRERfSU5WRU5UT1JZX0xPQ0FUSU9OLEFERF9VU0VSLEFERF9NQVRFUklBTF9JU1NVRSxWSUVXX0NBVEVHT1JZLEFERF9VU0VSX0lOVkVOVE9SWV9MT0NBVElPTl9NQVBQSU5HLFBFUklPRF9CQVNFRF9SRVBPUlQsREVMRVRFX1NFUlZJQ0VfVEFTSyxFRElUX1VTRVJfSU5WRU5UT1JZX0xPQ0FUSU9OX01BUFBJTkcsRURJVF9NQVRFUklBTF9QUk9DVVJFTUVOVCxFRElUX0NPTVBBTlksVklFV19NQVRFUklBTF9JU1NVRSxBRERfVVNFUl9UQUxVS19NQVBQSU5HLEVESVRfUkVXQVJEX1BPSU5ULE1PTlRITFlfUkVQT1JULFZJRVdfUkVXQVJEX1BPSU5ULEFERF9TQUxFU19UQVNLLFZJRVdfVVNFUl9JTlZFTlRPUllfTE9DQVRJT05fTUFQUElORyxWSUVXX0NPTVBBTlksRURJVF9UQVNLLEFTU0lHTl9VU0VSX1NBTEVTLFZJRVdfVVNFUixWSUVXX1NUT0NLX0RJU1RSSUJVVElPTixERUxFVEVfVVNFUl9JTlZFTlRPUllfTE9DQVRJT05fTUFQUElORyxERUxFVEVfU0FMRVNfVEFTSyxWSUVXX0lOVkVOVE9SWSxFRElUX1VTRVIsQ1JFQVRFX1RBU0ssVkVSSUZZX0NPTVBBTlksQ0hBVCxERUxFVEVfVVNFUl9UQUxVS19NQVBQSU5HLFZJRVdfQUxMX1NFUlZJQ0VfVEFTSyxERUxFVEVfSU5WRU5UT1JZLFZJRVdfTUFURVJJQUxfUFJPQ1VSRU1FTlQsRURJVF9DQVRFR09SWSxTQV9EQVNIQk9BUkQsVVNFUl9NQU5BR0VNRU5ULEFERF9NQVRFUklBTF9QUk9DVVJFTUVOVCxWSUVXX1NBTEVTX1RBU0ssRURJVF9NQVRFUklBTF9JU1NVRSxFRElUX1VTRVJfVEFMVUtfTUFQUElORyxSRVBPUlRfTUFOQUdFTUVOVCxBRERfQ09NUEFOWSxSRVNFVF9JTUVJLFZJRVdfU0NSQVBfREVUQUlMUyxUQVNLX01BTkFHRU1FTlQsVklFV19TRVJWSUNFX1RBU0ssQUREX1NUT0NLX0RJU1RSSUJVVElPTixFRElUX0lOVkVOVE9SWV9MT0NBVElPTixWSUVXX1VTRVJfVEFMVUtfTUFQUElORyxWSUVXX0lOVkVOVE9SWV9MT0NBVElPTixFRElUX0lOVkVOVE9SWSxUQVNLX0xJTUlUX0NPVU5ULERFTEVURV9JTlZFTlRPUllfTE9DQVRJT04sQ09ORklHVVJBVElPTlMsVklFV19VU0VSX1JPTEUsREVMRVRFX1RBU0tfUk9MRSxERUxFVEVfVVNFUl9ST0xFLFZJRVdfVEFTS19ST0xFLFVTRVJfTElNSVRfQ09VTlQsVEhFTUVfQ0hBTkdFLERFTEVURV9WRU5ET1JfTUFTVEVSLE9UQ19UQVNLLFZJRVdfVkVORE9SX01BU1RFUixBRERfVkVORE9SX01BU1RFUixWSUVXX01BVEVSSUFMX1JFVFVSTixBRERfVEFTS19ST0xFLEFERF9NQVRFUklBTF9SRVRVUk4sRU5BQkxFX0NPTVBBTlksQUREX1VTRVJfUk9MRSxERUxFVEVfQ0FURUdPUlksRElTQUJMRV9DT01QQU5ZLEFUVFJJQlVURVNfQ0hFQ0tfTElTVCxJTlZFTlRPUllfQlVMS19VUExPQUQsUEhPVE9fVVBMT0FELERFTEVURV9JTlZFTlRPUllfTUFTVEVSLEFERF9JTlZFTlRPUllfTUFTVEVSLERFTEVURV9TQ1JBUF9ERVRBSUxTLFZJRVdfVEFTSyxFRElUX0lOVkVOVE9SWV9NQVNURVIsQ0hBTkdFX1JFUVVFU1QsVklFV19TVE9DS19ERVRBSUxTLEVESVRfTE9HSU5fVFlQRSxFRElUX1RBU0tfUk9MRSxFRElUX0lTX0xJVkVfTE9DQVRJT05fTkVFREVELEVESVRfU0NSQVBfREVUQUlMUyxFRElUX1NFUlZJQ0VfVEFTSyxEQVNIQk9BUkQsVklFV19BTExfU0FMRVNfVEFTSyxTRVJWSUNFX1RBU0tfQlVMS19VUExPQUQsREVMRVRFX01BVEVSSUFMX1BST0NVUkVNRU5ULEFERF9TRVJWSUNFX1RBU0ssRURJVF9TQUxFU19UQVNLLERFTEVURV9VU0VSLE9UUF9DT01QTEVUSU9OLEVESVRfVVNFUl9ST0xFLEVOQUJMRV9VU0VSLENPTVBBTllfTUFOQUdFTUVOVCxSRVNFVF9QQVNTV09SRCxWSUVXX0lOVkVOVE9SWV9NQVNURVIsQUREX1JFV0FSRF9QT0lOVCxWSUVXX1VTRVJfTElWRV9MT0NBVElPTl9UUkFDS0VSLERJU0FCTEVfVVNFUixERUxFVEVfUkVXQVJEX1BPSU5ULEVESVRfVkVORE9SX01BU1RFUiIsImlhdCI6MTcyNDkzMjAxOSwiZXhwIjoxNzI0OTQwMDE5fQ.3BwI1vV9tsgIMbYpxKiwS0rVSsIv7WEcNmD-y4-tatcaVGZhIHrkOdtP8Z6c7NNDboo-94Kq79sv7AnmXj-IDQ"

export async function listWS() {
    const configs = {
        url: serverPath.bfil + "ws/wsmaster/getallwatershed",
        method: 'post',
        headers: { Authorization: `Bearer ${sessionStorage.getItem("token")}` }
    }
    try { const response = await axios(configs); return response.data; }
    catch (error) { console.error(error); throw error; }
}

export async function addWS(data: any) {
    const configs: AxiosRequestConfig = {
        url: `${serverPath.bfil}ws/wsmaster/addwatershed`,
        method: 'post',
        data: data,
        headers: {
            Authorization: `Bearer ${tkn}`,
            "Content-Type": "application/vnd.api+json",
        }
    };

    try {
        const response = await axios(configs);
        return response.data;
    } catch (error) {
        console.error('Error occurred while adding watershed:', error);
        throw error;
    }
}

export async function editWS(data: any, id: number) {
    const configs = {
        url: serverPath.bfil + `ws/wsmaster/updateWsById/${id}`,
        method: 'post',
        data: data,
        headers: { Authorization: `Bearer ${sessionStorage.getItem("token")}` }
    }
    try { const response = await axios(configs); return response.data; }
    catch (error) { console.error(error); throw error; }
}